version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: clientes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"             
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: